export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_ERROR = "CHANGE_PROFILE_ERROR";
export const SET_PROFILE = "SET_PROFILE";

export const LOADING_PROFILE = "LOADING_PROFILE";

export const LOADING_AVATAR_PROFILE = "LOADING_AVATAR_PROFILE";
export const LOADING_BANNER_PROFILE = "LOADING_BANNER_PROFILE";

